version: '3.2'

services:
  db:
    image: postgres:16
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - '5433:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata

  web:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '3001:3000'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      RAILS_ENV: development
      RACK_ENV: development
    stdin_open: true
    tty: true
    entrypoint: ./docker-entrypoint.sh
    volumes:
      - ./:/usr/src/app
    depends_on:
      - db

volumes:
  pg_data:
    driver: local
